# Numpy Baics 

In [2]:
#Importing Numpy 
import numpy as np

np.array([7.4,8,12,5,46,23,45])  #Calling Numpy method

#float array

array([ 7.4,  8. , 12. ,  5. , 46. , 23. , 45. ])

In [3]:
np.array([2,45,65,34,])  # Integer array

array([ 2, 45, 65, 34])

### Working with  different data types using Numpy 

In [11]:
np.array([4,45,32,12], dtype="str") # Allocating string 


array([ 3., 15., 47., 63.], dtype=float32)

In [12]:
np.array([3,15,47,63], dtype="float32")


array([ 3., 15., 47., 63.], dtype=float32)

In [15]:
array_1 = np.arange(15).reshape(3,5)
array_1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [21]:
array_1.shape  # for shape of array


(3, 5)

array_1.dtype.name # Name of the data type

In [20]:
array_1.ndim # Dimmension of array

2

### Creating Numpy Array from Scratch Using multiple Methods

In [22]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((4,5), dtype="str")

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

In [24]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(2,23, 3) # Specify the first number, last number, and the step size.

array([ 2,  5,  8, 11, 14, 17, 20])

In [28]:
np.linspace(1,50,10)  # Create an array with values that are spaced linearly in a specified interval

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [31]:
np.random.random((4,4))  # For creating 2D array with random Values


array([[0.72739553, 0.43228093, 0.9666427 , 0.47688936],
       [0.59612897, 0.56349631, 0.99157191, 0.51027069],
       [0.11652922, 0.48231728, 0.03470468, 0.15399903],
       [0.6140663 , 0.0267664 , 0.77248644, 0.68448456]])

In [35]:
np.random.normal(0,1,(3,3))  #Normal used to give distruted values with mean 0 and standard deviation 1

array([[ 1.10550632,  0.74422269,  0.13084447],
       [ 0.28215272, -0.23014503, -2.01944876],
       [ 0.53220698,  1.26333568,  1.48586286]])

### Concatination

In [37]:
x_axis = np.array([[1,2],[2,3]])
y_axis = np.array([[5,6]])

np.concatenate((x_axis,y_axis), axis=0)  # Using this method we can concatenate 

array([[1, 2],
       [2, 3],
       [5, 6]])

### Indexing and slicing

In [38]:
employee_no = np.array([1,2,3,4,5])
employee_no[0]

1

In [39]:
employee_no[0:5]

array([1, 2, 3, 4, 5])

In [40]:
employee_no[1:]

array([2, 3, 4, 5])

In [41]:
employee_no[-2:]

array([4, 5])

In [42]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [43]:
print(a[a<5])

[1 2 3 4]


In [44]:
# Working with objects 
five_steps_up = (a>=5)
print(a[five_steps_up])

[ 5  6  7  8  9 10 11 12]


In [45]:
# Conditional Statement as a  objects for array
condition = ((a>5) & (a<12))

print(a[condition])

[ 6  7  8  9 10 11]


### Broadcasting

In [68]:
data = np.array([1.0,2.0]) # Operatiion between array and single number is 
                            #called as Broadcasting it is also used to make two dimensional array
data * 5

array([ 5., 10.])

In [48]:
data.max()

2.0

In [49]:
data.min()

1.0

In [53]:
data = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [52]:
data.sum()

4.8595784

In [58]:
data= np.random.randint(100, size=(3,3))
data

array([[31, 34,  1],
       [96, 51,  1],
       [69,  6, 22]])

In [60]:
data.min(axis=0)

array([31,  6,  1])

In [62]:
# To Find unique values
data= np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(data)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [65]:
# Uniform sample
np.random.uniform(1,10,size =(3,3))

array([[7.51483662, 7.36441916, 4.39181672],
       [3.05271623, 3.70787853, 4.95288484],
       [5.68848023, 5.45452047, 9.47164922]])

In [66]:
#argmax and argmin

data = np.array([[0.12,0.64,0.19,0.05]])
np.argmax(data)

1

In [67]:
np.argmin(data)

3